name: Semgrep Security Scan
on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sundays
jobs:
  semgrep-scan:
    name: Semgrep Code Scanning
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Semgrep Scan
        uses: semgrep/semgrep-action@v1
        with:
          publishToken: ${{ secrets.SEMGREP_TOKEN }}
        env:
          # Set your Semgrep token as a secret in GitHub repository
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_TOKEN }}
          SEMGREP_TIMEOUT: 300
        continue-on-error: true  # This ensures the workflow doesn't fail when Semgrep finds issues
