name: TruffleHog Secret Scanning

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday at midnight

jobs:
  secret-scan:
    name: 🔒 Secret Scan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: 
          - {name: 'frontend', path: 'jai3747/crud-app-frontend'}
          - {name: 'backend', path: 'jai3747/crud-app-backend'}
      fail-fast: false
    
    steps:
      - name: Clean workspace
        run: |
          rm -rf * 
          rm -rf .git
        
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.repo.path }}
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0
          clean: true
          force: true
        
      - name: TruffleHog Scan
        uses: trufflesecurity/trufflehog@v3.63.3
        continue-on-error: true
        with:
          path: .
          base: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.sha || 'HEAD~50' }}
          head: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || 'HEAD' }}
          extra_args: --debug --only-verified --json --output trufflehog-${{ matrix.repo.name }}-report.json
        
      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.repo.name }}-secret-scan-report
          path: trufflehog-${{ matrix.repo.name }}-report.json
          retention-days: 30

      - name: Check for secrets
        id: check_secrets
        run: |
          if [[ -s trufflehog-${{ matrix.repo.name }}-report.json ]]; then
            SECRETS_COUNT=$(grep -o "\"Detector\"" trufflehog-${{ matrix.repo.name }}-report.json | wc -l)
            echo "Found $SECRETS_COUNT potential secrets in ${{ matrix.repo.name }} repository!"
            echo "::warning::Found $SECRETS_COUNT potential secrets in ${{ matrix.repo.name }} repository!"
            cat trufflehog-${{ matrix.repo.name }}-report.json
            exit 1
          else
            echo "No secrets found in ${{ matrix.repo.name }} repository. All clear!"
          fi
