name: Semgrep Security Scan
on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sundays

jobs:
  semgrep-scan:
    name: Semgrep Security Scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags
      
      - name: Install Semgrep
        run: pip3 install semgrep
      
      - name: Run Semgrep Scan
        run: |
          semgrep ci --verbose
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_TOKEN }}
        continue-on-error: true  # This ensures the workflow doesn't fail when Semgrep finds issues
      
      - name: Run Semgrep Local Scan (Fallback)
        if: ${{ failure() }}
        run: |
          semgrep --config=auto --output=semgrep-results.json --json .
        continue-on-error: true
      
      - name: Display Findings Summary
        if: always()
        run: |
          if [ -f semgrep-results.json ]; then
            echo "Semgrep findings summary from local scan:"
            cat semgrep-results.json | jq '.results | length' | xargs -I{} echo "Total findings: {}"
          else
            echo "No local Semgrep results file found"
          fi
      
      - name: Save Results to Job Summary
        if: always()
        run: |
          echo "## Semgrep Security Scan Results" >> $GITHUB_STEP_SUMMARY
          echo "Scan completed. Check the logs for details on any findings." >> $GITHUB_STEP_SUMMARY
