name: Semgrep Security Scan
on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sundays

jobs:
  semgrep-scan:
    name: Semgrep Security Scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags
      
      - name: Install Semgrep
        run: pip3 install semgrep
      
      - name: Run Semgrep Scan
        run: |
          semgrep --config=auto --output=semgrep-results.json --json .
        continue-on-error: true  # This ensures the workflow doesn't fail when Semgrep finds issues
      
      - name: Display Findings Summary
        if: always()
        run: |
          if [ -f semgrep-results.json ]; then
            echo "Semgrep findings summary:"
            cat semgrep-results.json | jq '.results | length' | xargs -I{} echo "Total findings: {}"
            
            # Optional: Display first few findings
            cat semgrep-results.json | jq '.results[:5] | .[] | {rule_id, path, line}' || echo "No findings to display"
          else
            echo "No Semgrep results file found"
          fi
      
      - name: Upload Scan Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: semgrep-results
          path: semgrep-results.json
          retention-days: 7
